/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mfp;

import java.util.Scanner;

public class App {
    
    
    public static void main(String[] args) {
        
    Scanner scan = new Scanner(System.in);
    
    int a;
    int b;
    int c;
    int m;
    int n;
    
    m = scan.nextInt();
    n = scan.nextInt();
    
    a = (m*m) - (n*n);
    b = 2*m*n;
    c = (m*m) + (n*n);
    
    
    
    
    System.out.print(a + " " + b + " " + c);
    
}
    
}

