/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;
import java.util.Date;
import model.Adolescente;
import model.Orientador;
import model.Orientacao;
import controller.OrientadorController;

public class App {
    

    public static void main(String[] args) {
        
        OrientadorController orientadorController = new OrientadorController();
        Orientador orientador1 = new Orientador();
        orientador1.setId(1);
        orientador1.setNome("Nathalia Almeida");
        
        Orientador orientador2 = new Orientador();
        orientador2.setNome("Lucas");
        
       orientadorController.save(orientador2);
        
        
       
        
        
        System.out.println(orientadorController.getAll());
    }
}
