/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;
import java.util.Date;
import model.Adolescente;
import model.Orientador;
import model.Orientacao;

public class App {
    

    public static void main(String[] args) {
        
        Orientador orientador1 = new Orientador();
        orientador1.setId(001);
        orientador1.setNome("Nathalia");
        
        System.out.println(orientador1.toString());
        
        Adolescente adolescente1 = new Adolescente();
        System.out.println(adolescente1.toString());
        adolescente1.setNome("Lucas");
        adolescente1.setDataInicio(new Date(24/03/2023));
        adolescente1.setDataNasc(new Date(02/07/1991));
        adolescente1.setOrientador(orientador1);
        
        System.out.println(adolescente1.toString());
        
        
    }
}
